// desenvolver action conforme nescessidade
export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_SUCCESSFUL = 'REQUEST_SUCCESSFUL';
export const GRAVATAR_EMAIL = 'GRAVATAR_EMAIL';
export const SAVE_USERNAME = 'SAVE_USERNAME';
export const ADD_SCORE = 'ADD_SCORE';
export const INCREASE_ASSERTIONS = 'INCREASE_ASSERTIONS';
export const RESET_LOGIN = 'RESET_LOGIN';
export const RESET_FETCH = 'RESET_FETCH';
